### ISSUE TITLE
#info

### ISSUE THREAD

**Issue by tgbetauser** [Chooloo/call_manage#1]
Hi, great app, congratulations!

What are end call and answer call timer?

**Comment by roeiedri** [comment]
Hi tgbetauser! 
First of all thank you very much.
When someone calls you, instead of answering on the spot you can set a timer to answer or reject.
(This option was made with a client's request in mind)

**Comment by tgbetauser** [comment]
Mh so, if i don't answer for 10 seconds, call terminate itself? This is reject right? But I don't understand about answering, call open itself with timer?

**Comment by roeiedri** [comment]
Answering simply answers after 10 second, we did that feature with a client's request in mind

**Comment by tgbetauser** [comment]
Yes but I mean: after or before to answer a call?

**Comment by NuclearGandhi** [comment]
When you start the answer timer - after it reaches 0:00 - it will answer the call. Before that, it won't do anything. We are planning that it will silence the ringing white the timer is still counting down.
