### ISSUE TITLE
Call type icon missing for rejected calls

### ISSUE THREAD

**Issue by zhirzh** [Chooloo/call_manage#100]
**Describe the bug**
Call type icon missing for rejected calls

**To Reproduce**
1. Reject an incoming call
1. Check the call log in Recents screen

**Screenshots**
![5 - call type icon missing for rejected calls](https://user-images.githubusercontent.com/8132723/94452212-ed3baf80-01cc-11eb-93e6-ede215543388.gif)

**Comment by roeiedri** [comment]
Are talking about the bug where a rejected call will sometimes show an incoming call icon?

**Comment by roeiedri** [comment]
Please see if this solves your issue

**Comment by roeiedri** [comment]
(The latest version)

**Comment by zhirzh** [comment]
fixed in f01025e633b0c5adb594615d735e615b2df12ab8

**Comment by zhirzh** [comment]
AFAIK, [`Calls.REJECTED_TYPE`][1] denotes incoming calls rejected by the user. By that definition, I don't feel the icon used conveys the correct message.

<img width="100" alt="Screen Shot 2020-09-30 at 11 51 21 PM" src="https://user-images.githubusercontent.com/8132723/94724594-26fce980-0378-11eb-9440-575209295c38.png">

[1]: https://developer.android.com/reference/android/provider/CallLog.Calls#REJECTED_TYPE
