### ISSUE TITLE
Recents screen doesn't show call logs for numbers not saved in contacts

### ISSUE THREAD

**Issue by zhirzh** [Chooloo/call_manage#103]
**Describe the bug**
Recents screen doesn't show call logs for numbers not saved in contacts

**To Reproduce**
1. Call a number that is not saved in contacts
1. Check Recents tab for call logs

**Screenshots**

Native dialer shows call logs

<img width="400" src="https://user-images.githubusercontent.com/8132723/94535669-769bc200-025f-11eb-859b-ae813d792b14.png"/>

<br/>
But Koler app doesn't show any logs
<img width="400" src="https://user-images.githubusercontent.com/8132723/94535677-7a2f4900-025f-11eb-8f18-cb9b45c4121d.png"/>

**Comment by roeiedri** [comment]
Koler doesnt show calls that has been placed before Koler's intallation
You sure u called someone AFTER u installed Koler?

**Comment by zhirzh** [comment]
After spending some time debugging, I have narrowed down the issue to the content resolver query in RecentsCursorLoader (see below)

https://github.com/Chooloo/call_manage/blob/f01025e633b0c5adb594615d735e615b2df12ab8/app/src/main/java/com/chooloo/www/callmanager/cursorloader/RecentsCursorLoader.java#L78-L83

When `contactName` is an empty string, the selection string returned looks like: `name LIKE '%%' AND ...` which will filter out records where cached name is `NULL`, since this column is _typically filled in by the dialer app_ and _is not guaranteed to be present_ (see [here][1])

[1]: https://developer.android.com/reference/android/provider/CallLog.Calls#CACHED_NAME
