### ISSUE TITLE
App crashes when i press 1 on the dialer

### ISSUE THREAD

**Issue by wdtheprovider** [Chooloo/call_manage#104]
**Describe the bug**
When entering 1 the app crashes but when i start with 2 and continue typing like 234717911123 it works fine. 

**To Reproduce**
1. Open the app ' '
2. Click on 'dialer'
3. I enter  *1 (App crashes)

**Expected behavior**
I was expecting to start typing the value  of "1" first like *111*500#. This ussd code checks available balance in network

**Screenshots**
![CoolCaller](https://user-images.githubusercontent.com/49024101/95571526-e1e84f80-0a28-11eb-8d72-85828e25c951.PNG)

**Smartphone (please complete the following information):**
 - Device: Huawei Honor 8x
 - OS: Android 10
 
**Additional context**
More info is available on the screen shot. Thank you

**Comment by roeiedri** [comment]
What version of Koler are u using?

**Comment by roeiedri** [comment]
I had a log outside of a try block trying to parse a number by national format
Deleted it :)
