### ISSUE TITLE
Koler V0.2.7 - Doesn't Recognize Digits/Phone Number If Shared/opened With Koler

### ISSUE THREAD

**Issue by realrufans** [Chooloo/call_manage#11]
#### Expected behavior
To successfully load or recognize numbers if the user share or open the number with Koler, from another app.

#### Actual behavior
It loads the Recent Page instead of ```Table_Numbers``` after a number is opened with it.
 

#### How to reproduce
-  Share a number into Koler from another app ( I used WhatsApp) )
- You will notice that It won't recognize it while other similar applications does.

##### Browser/App version:
Koler v0.27

##### Operating system:
Android 0

#### Recording Of The Bug

![MNML-May16-0407-1558019363831.gif](https://cdn.steemitimages.com/DQmeBjAy7Y3xGfkWnuApcZxmLRi2LGAnnjqWiLx3HsGnh8m/MNML-May16-0407-1558019363831.gif)

**Comment by NuclearGandhi** [comment]
Flagged as enhancement as this is not a feature yet implemented

**Comment by realrufans** [comment]
It's all good. Would be expecting it someday. 🕺
