### ISSUE TITLE
Add Privacy Policy and contributors guide document

### ISSUE THREAD

**Issue by HarryHeights** [Chooloo/call_manage#13]
Hello, I'm Harry. I engage in creating documents for open source projects. It's part of my contribution in helping open source projects. One of the documents I engage in creating is a privacy policy. The privacy policy will give details about user information collection, use and security. I really don't know if you externally collect user information, but, if you don't, it's good to let end users know via a privacy policy.
Contributor's guidelines is also an important document that will help prospective collaborators contribute easily to your project.

I'll love to hear your thoughts on this.

**Comment by NuclearGandhi** [comment]
Hey Harry， we currently have a simple privacy policy for our app: https://sites.google.com/u/1/s/1bv33KFcCcJwTIDtOyk4V0AkNe_qOEVap/edit

If you think anything needs to be changed, we would love to hear.

**Comment by HarryHeights** [comment]
The page wouldn't open though. But if you have a privacy policy, then it should be good.  It'll be great if it could be accessed from/on the app.

**Comment by NuclearGandhi** [comment]
Yeah sorry this is the correct link: https://sites.google.com/view/koler-privacy-policy/home?authuser=1.
We will implement it in the app. Thank you!

**Comment by HarryHeights** [comment]
![Screenshot_2019-05-17-09-49-28-218_com android chrome](https://user-images.githubusercontent.com/40593824/57915629-17ffbf00-7889-11e9-8b16-bc15091338a7.png)

Is that all the content of the policy in that image @NuclearGandhi ?
