### ISSUE TITLE
[Koler][v0.2.8]Unable to cut a call if pressed  number from dial pad while calling. 

### ISSUE THREAD

**Issue by maaudrana** [Chooloo/call_manage#14]
<h4>Actual Behaviour </h4>
I can not cut the call if i clicked a number in the dial pad.
<h4>Expected behavior</h4>
Expected that i can cut the call after dialing number or i can go back to dialing page after clicking the back button.
<h4>How to reproduce</h4>
<ol>
<li>Install the apps and open the app</li>
<li>Call someone </li>
<li>Click dial pad and input a number.</li>
<li> Click back to go to the dialing page to cut the call</li>
<li>See you can not cut the call and you will not found the dialing page.</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:v0.2.8</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/EUeT-mYC06Q">https://youtu.be/EUeT-mYC06Q</a>

**Comment by roeiedri** [comment]
The problem is that you need to swipe down in order to collapse the keypad, then you can answer.
Due to your complaint we will add an indicator and will disable the option to go back while in an active call.
