### ISSUE TITLE
,[koler][v0.2.8]The app unable  to fetch ussd data.

### ISSUE THREAD

**Issue by maaudrana** [Chooloo/call_manage#15]
<h4>Actual Behaviour </h4>
The app can not fetch ussd call data.I see in the recent dial section that it deleting # sign,this causing the issue i think.
<h4>Expected behavior</h4>
Expected that i can view my sim card balance by dialing ussd code.I dialed *778# and called but nothing happening. </h4>
<h4>Step to reproduce </h4>
<ol>
<li>Install the apps and open the app</li>
<li>Go to contact</li>
<li>Click dial pad and input any ussd related to your sim card.</li>
<li>call and the error.</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:v0.2.8</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/5vlU09oIDy4">https://youtu.be/5vlU09oIDy4</a>

**Comment by NuclearGandhi** [comment]
Since I can't test USSD on my device, could you please test it on this version: [test](https://www.mediafire.com/file/0k2r3veg4j5ar3x/app-release.apk/file)

**Comment by NuclearGandhi** [comment]
Possible fix on e7259b5c45b2c7236a8d3c13606c68e454bb9982

**Comment by cckole** [comment]
Hello, I can see that this issue has been closed and fixed, but the app can't still fetch #ussd data. I tried using it in the new version but, it dialled like a normal call. See the details in the video below.

https://youtu.be/NV-FGypH-eQ
