### ISSUE TITLE
The app unable to open IMEI by using dial pad

### ISSUE THREAD

**Issue by lushohammy** [Chooloo/call_manage#16]
#### Expected behavior
user should be able to see their phone imei number with typing dial-pad

#### Actual behavior
when i typing in dialpad ( * # 0 6 # ) in koler app it shows nothing .

#### How to reproduce
* open the koler app
* type ( * # 0 6 # ) for imei number
* see the bug

#### Operating system 
* App version:v 0.2.8
* Android v8.1.0 OPMI

#### Recording Of The Bug
https://youtu.be/8DBcPlee75Y

**Comment by roeiedri** [comment]
hey, i worked a bit on the code and overall improved it, it seems like this got fixed on the way, im closing this issue for now.
if its still an issue please open this again and ill take a look
