### ISSUE TITLE
App not selecting sim and call not connecting

### ISSUE THREAD

**Issue by cckole** [Chooloo/call_manage#19]
### Description
I tapped a number from my contacts list to place a call and discovered the number started dialing without asking which sim card I wanted to use. That isn't the main point because the app might be designed that way, and if not, then it can be seen as a bug. However, the main issue is that the dialed number will start reading and no call will be placed. That means the call is not connecting. 

### Expected behaviour

My expectation was to use either of my sim card for calls, and also see the dialled call connected.

### Steps to reproduce

After launching the app

- accept the whole permission
- Dial a number from your contact list and note the behavior. The call will start  without asking to select sim card and the call will not be connected.

### Device used

Techno spark k7
OS: Android 7.0

### Reproducing the behavior
https://youtu.be/nxew0-xnGtk

**Comment by roeiedri** [comment]
Im reopening this issue as i dont have the tools to confirm it has been solved.
Could you test it in the latest version [https://github.com/Chooloo/call_manage/commit/0ca6c6047200d469821e2853db0320d5178d3671](url) and write here weither it has been solved?
To use the feature go in the settings page and click 
"Sim Selection" the choose a sim card

**Comment by cckole** [comment]
Hello, I've tried using it but its not selecting sim. Calls not connecting as well. Sorry for the delay in response.

**Comment by cckole** [comment]
Yes I have the right settings in place. My SIM are showing in the settings.

**Comment by roeiedri** [comment]
Could u test it again and tell us wither the bug still happens?

**Comment by roeiedri** [comment]
Please open this issue again if you've tested it and it's still not working the way it should be

**Comment by sparevermicelli** [comment]
Hi,
this bug is not yet solved.

When no SIM is selected in the contact as default, then even though the Koler is asking for SIM - no call is placed (no ring tone, always "dialing")
When I select for example SIM1 as default for one contact, then in Koler I am asked again to choose SIM (Here I'd also argue that it's not a correct behavior, or?). When I now choose SIM2, the call is still placed under default SIM1.
