### ISSUE TITLE
Add "Cursor" and Ability to Select, Copy and Paste numbers to the dialer

### ISSUE THREAD

**Issue by jubreal** [Chooloo/call_manage#20]
#### Components
The app is in its test phase for volunteers who are ready to contribute to it. As an open-source enthusiast, I am really glad to contribute to this project.
After downloading the app and in the course of my exploration, I found out some very important features that can enhance user experience which are currently missing in the app. Non-implementation of these features will negatively affect the app, as users might lose interest in the app for the lack of these features. So, I'm suggesting the implementation of "Cursor and Ability to Select, Copy and Paste numbers to the dialer".
#### Proposal Description
Koler app is a call managing app as earlier mentioned, and it thus has a dialer page(dialing window) where users can input and dial numbers. But while using it, I found some things missing in the dialer page which I'm now proposing to be added. They are;
- **Addition of Cursor:** While trying to make a call with, after inputting the phone number to call, I noticed I made a mistake in between the number and I had to delete a number and replace it, so I tried going straight to the point of the mistake to make the correction, but to my surprise, there is no such ability, which means I had to delete all the other numbers that were after the point where the mistake occurred. This was really stressful and time wasting.
So, I'm suggesting that "Cursor" should be introduced to the app, which users can move anywhere they plan to use it.

- **Ability to Select, Copy and Paste numbers:**  This feature is also missing in the Koler app. I mean the developer said the app was designed keeping the users in mind, then they have to know that basic ability to select, copy and paste is necessary to ease the use of the app. Most times, users might need to paste a phone number copied from another place on the device directly and place a call immediately or even might want to copy a phone number directly from the app, sadly this is not currently possible using the app. I really wish the developers will implement this feature also.
#### Mockups / Examples
Below are pictorial illustrations of how the features I recommend can be implemented by the Developer.

This is how the app currently looks like without the feature![Screenshot_20190518094803.png](https://files.steempeak.com/file/steempeak/jubreal/1hx3rQ6F-Screenshot_20190518-094803.png)
This is a picture showing how the "Cursor" feature can be implemented(Note that the cursor position can be changed to any point, it's just static in this mock up because it's an image)![PicsArt_051810.02.35.png](https://files.steempeak.com/file/steempeak/jubreal/UCtmCsYG-PicsArt_05-18-10.02.35.png)
This is a picture showing how the "Select, Copy and Paste" feature can be implemented in the app![PicsArt_051810.05.14.png](https://files.steempeak.com/file/steempeak/jubreal/3noHQqEF-PicsArt_05-18-10.05.14.png)

#### Benefits
The benefits of the features suggested above are as follows:
- **Cursor Addition** will allow users to carry tasks such as deletion of a particular number or addition of number at a particular point without having to delete the "unconcerned ones".
- **Select, Copy and Paste** will save users time and reduce the stress involved in typing number every time. This will also allow users to transfer numbers easily to and from the app.
#### Conclusion
In general, Implementing these features will go a long way to improve the application. It will increase user experience positively, thereby increasing the user base of the Koler app.
I hope, App developer implements this feature very soon.

Thank You.

**Comment by roeiedri** [comment]
At first it actually worked the way you're suggesting but changed it, thank you for your advice
