### ISSUE TITLE
Koler couldn't fetch names when searched from `recent calls`. I.e, Search feature not working in the `Recent` feature.

### ISSUE THREAD

**Issue by cckole** [Chooloo/call_manage#21]
**Describe the bug**
The `Recent` feature on koler displays all the received, and dialed calls altogether, so I searched for one number that have called me, to save the time of scrolling to find the name. When I clicked on the search Icon and typed the name of the person I want to call, the name was not fetched.

**To Reproduce**
- Launch the app
- Accept all permissions
- Click on `Recent`
- You will see the search icon below to the left side. Click on it and type the name of the person you want to call. (I made sure the person is on the call list)
- The name will not be fetched.

**Expected behavior**
When I typed the name, I expected koler to fetch any name related to what I’m typing and eventually fetch the main name I typed just as it’s working when you search for names in the `contact`. The search should be able to seach the contact I typed.

**Screenshots**
https://youtu.be/0kgBzmZXoro

**Smartphone (please complete the following information):**
 - Device: [Tecno spark k7]
 - OS: [Android 7.0]
 - App Version [v.0.2.9]

**Comment by cckole** [comment]
This is working fine now. I was able to search conveniently. Very okay. Thanks for the fix.

**Comment by roeiedri** [comment]
You are welcome, if theres any inconvenient let us know
