### ISSUE TITLE
Incoming call from numbers not stored is displayed as anonymous

### ISSUE THREAD

**Issue by cckole** [Chooloo/call_manage#22]
**Describe the bug**
I had an incoming call and checked my phone screen to see who it was, but no number/name was displayed. When I picked the call, I discovered it was a number that isn’t stored on my phone. After the call, I tried calling my line with a number stored on my device, and the caller’s name showed. I later discovered that if any number that isn’t stored on the device enters as an incoming call, it is displayed as anonymous.

**To Reproduce**
- You can notice this if a number not stored on your device enters as an incoming call, or
- Call your line with a number not stored on your device and note the error.

**Expected behavior**
I was expecting to see the number that called whether or not stored on my device.

**Reproducing the behaviour**
https://youtu.be/tb0AK2jDzSU

**Smartphone**
- Device: [Tecno spark k7]
- OS: [Android 7.0]
- App Version [0.2.9]

**Comment by roeiedri** [comment]
It already has been fixed in the currently developed version, once finished you'll get the update.

**Comment by cckole** [comment]
That's cool. Will be expecting the new version. Thanks.

**Comment by roeiedri** [comment]
Does it happen always no exceptions?

**Comment by roeiedri** [comment]
This problem has been solved, if it appears again please contact us.
Thank you.

**Comment by cckole** [comment]
Oh! That's fine. I will get back with info as soon as I have one. Thanks.

**Comment by cckole** [comment]
Working fine.
