### ISSUE TITLE
Speaker not working

### ISSUE THREAD

**Issue by AlanSanchezP** [Chooloo/call_manage#23]
I use a redmi 6 phone (miui 10, android 8.1), and when receiving calls I usually use the speaker function so that I can do other things at the same time.

Problem is, since I downloaded Koler, this function doesn't always work. It does sometime, but I can't find any pattern that determines whether it works or not. :pensive:

**Comment by roeiedri** [comment]
Do you use Koler as your default dialer or does this bug happens when you use your built in ongiong call screen?

**Comment by roeiedri** [comment]
It has been solved, if it happens again please contact us.
Thank you.

**Comment by AlanSanchezP** [comment]
I have koler as default dialer

**Comment by csetanmayjain** [comment]
I also face this similar problem on many devices like Xiaomi Redmi Note 5, Vivo, Oppo.
I also try to implement loudspeaker functionality but it depends model to model.
In some of devices it works, while in some not.
Hope you find a solution for this problem soon and fix it

**Comment by roeiedri** [comment]
Were back in business
Could you describe more about the problem, when does it happen and how?

**Comment by yasirkhan8691** [comment]
On some devices of mi vivo and one plus the speaker doesn't work.

**Comment by KhushrajRathod** [comment]
@roeiedri This bug occurs only when Koler is the default dialer, because otherwise the calling screen is of the default dialer instead of Koler. The speaker button seems to do nothing - If audio is being transmitted over bluetooth, it continues being transmitted, and if the audio is being played via earpiece, it will continue being played via the earpiece. This bug occurs on Redmi 7A at least, running phhusson's AOSP GSI

**Comment by adityadhiman** [comment]
Can be resolved if we use public method **setAudioRoute(CallAudioState.ROUTE_SPEAKER)**  of class InCallService

**Comment by adityadhiman** [comment]
> Can be resolved if we use public method **setAudioRoute(CallAudioState.ROUTE_SPEAKER)** of class InCallService

@roeiedri

**Comment by roeiedri** [comment]
Is this still an issue?

**Comment by KhushrajRathod** [comment]
> Is this still an issue?

Yes, I've just reinstalled koler and tested it

**Comment by KhushrajRathod** [comment]
@roeiedri Has this been fixed?
