### ISSUE TITLE
When I tried to dial a number on the app, it re-direct me to my normal phone caller

### ISSUE THREAD

**Issue by darewealth** [Chooloo/call_manage#27]
**Describe the bug**

I wanted to call from the app and when I clicked the number I want to call, I got redirected to my phone default caller.

**To Reproduce**

1. Open the app
2. Pick any number and dial. 
3. Note the issue

*Expected behavior**

I expect that I should be able to use the app to call out because it works well on my second device. (Andriod 7.0)

**Screenshots**
https://youtu.be/m6dDWy8zpdc

**Smartphone**
 - Device: [itel]
 - OS: [6.1]
 - Version [0.3.1]

**Comment by girubhai** [comment]
Same issue with Xiaomi devices.

**Device Details**

- SDK:23,
- Brand:Xiaomi,
- Model:Redmi 3S

**Comment by roeiedri** [comment]
Thank you very much for your feedback
We have been offline for a while now but we are back
The problem was that our app simply kept crashing when trying to open the in call screen, we fixed it and it will be in the next update
