### ISSUE TITLE
Bug: The app trigger my mobile vibration.

### ISSUE THREAD

**Issue by darewealth** [Chooloo/call_manage#28]
**Describe the bug**

When I dialed a number on my on with my phone set to loud, which I mean my phone is not mute or in vibration. After I dialed a number and cut the call, the app will trigger my mobile vibration. 

**To Reproduce**
1. Open the app
2. Dail a number, and make sure your phone is on sound
3. Cut the call and note the bug

**Expected behavior**

I don't expect that when I cut a call it will trigger my vibration. 

**Screenshots**
https://youtu.be/RoVo4Z2uU_c

**Smartphone**
 - Device: [Gionee X1]
 - OS: [7.0]
 - Version [0.3.1]

**Comment by revuwa** [comment]
Same behaviour here.
After calling any contact over the app, and finally hanging up, the [ring volume] will be reduced to 0% and so the phone is set to [vibrate] (after every single call).

**Smartphone**

- Device: [Moto G5]
- OS: [9.0]
- Version [0.3.1]
