### ISSUE TITLE
App doesn't return to the call in progress after using the dial app during a call.

### ISSUE THREAD

**Issue by iamowomizz** [Chooloo/call_manage#31]
**Describe the bug**
When ever I make a phone call on the app and during the phone call I make use of the the dial pad, I now try to go back to the call in progress to hang up I can't cause the app just stays same even after pressing the back button.

**To Reproduce**
1. Launch the app
2. Click on any number to make a call
3. During the call click on the dial pad, 
4. Now try to go back to the call in progress to be able to hang up

**Expected behavior**
I expect the app to go back to the call in progress so I can be able to hang up the call.

**Smartphone (please complete the following information):**
 - Device: [infinix s2pro]
 - OS: [Android 7.0]
 - Version [Version 0.3.1 ]

**Comment by csetanmayjain** [comment]
I also face similar problem in Xiaomi Redmi Note 5, and Vivo, Oppo devices.
