### ISSUE TITLE
Koler doesn't display name 

### ISSUE THREAD

**Issue by pravissw** [Chooloo/call_manage#32]
When a contact is saved with country code in the beginning, say +91 844xx xxxxx, it doesn't display the name of the caller but when I edit the contact to 91 844xx xxxxx, it does. 

**To Reproduce**
1. Go to contacts
2. Select a contact whose name is displayed when they call
3. Edit the number, adding the country code (+XXX) before the number

**Expected behavior**
The name of the contact will no longer be displayed, when they call. Instead, something like %2B(country code)(phone number)

**Screenshots**
![IMG-20190629-WA0010](https://user-images.githubusercontent.com/40398726/60379948-2ca8a880-9a2c-11e9-8d8e-7546cacef290.jpg)
![Screenshot_20190629-103203](https://user-images.githubusercontent.com/40398726/60379950-3500e380-9a2c-11e9-8341-cf14614da507.png)

**Smartphone:**
 - Device: Motorola one power
 - OS: Android 9
 - v0.3.1

**Comment by kentone** [comment]
Im having the same issue, it might be related with non numeric characters on the phone number?

**Comment by resom78** [comment]
Got the same issue too... I have all my numbers coded with "+33" at the beginning but it doesn't change anything!

**Comment by roeiedri** [comment]
Its a bug that occurred in the latest update, we will fix this as soon as possible

**Comment by roeiedri** [comment]
Hey were back after a long break
We think we have fixed it
Were rolling a new major update, be sure to check it out and please open the issue if the problem happens again
