### ISSUE TITLE
The Koler App keeps crashing after few seconds into a call

### ISSUE THREAD

**Issue by dongentle2** [Chooloo/call_manage#33]
Describe the bug
Each time I make a call and end it few minutes into the call,  the application crashes almost immediately. This is a major issue as it bars me from enjoying the full benefits of the application. I enjoy the application and would love of this is resolved. 

** Steps To Reproduce**

Launch the app.
Click on the contact you want to call. 
End the call after few seconds into the call. 
The app crashes after that. 

Expected behavior
I expected the application to return me to the homepage to enable me perform the basic functionality of the application. 

Screen recording
https://youtu.be/mD8LBDV6uoE

Test Environment

Device: Infinix Hot 7 Pro
OS: Android 9.0
Software version: Koler version 0.3.1
Logcat
Here is the full Inbuilt android logcat to help you. 

[bugreport-H624EF-PPR1.180610.011-2019-07-03-15-21-56.txt](https://github.com/Chooloo/call_manage/files/3356179/bugreport-H624EF-PPR1.180610.011-2019-07-03-15-21-56.txt)

**Comment by macspeaks** [comment]
I've been experiencing the same issue. Pls kindly fix it. Nevertheless, it's a great app.
