### ISSUE TITLE
App doesn't get back to the call when dialpad is used

### ISSUE THREAD

**Issue by syedubair** [Chooloo/call_manage#34]
**Describe the bug**
When we're in a call and open the dial pad and try to note a number or anything, after dialing those digits when we try to get back by pressing the back button, the app doesn't respond at all. So whenever we want to cut the call we are not able to do so unless we remove the app from recents. I think this is something major that needs to be fixed. 

**To Reproduce**
1. Dial a number from your contact list. 
2. During the call, press on the dialpad. 
3. Press any digit or even if you don't press any digit and then try to get back on the call. 
4. You can't go back. The back button doesn't work at all. 

**Expected behavior**
During a call when you're trying to write a number after opening the dialpad of the app, you should be able to get back to your call where you can close your speaker after keeping it on, or mute, or end call. You're not able to do so because the back button doesn't work after you've opened the dialpad, which is unexpected and it's expected to get back on that screen normally. 

**Video**
https://youtu.be/K2Zm-orNf3g

 - Device: [Motorola Moto G5 Plus]
 - OS: [Android Oreo 8.0]
 - Version [v0.3.1]

**Comment by roeiedri** [comment]
Hey first of all thank you for reporting the problem.
I've fixed that and it will be available as soon as well roll out another version.
Btw did you know you can swipe the dialpad down? just a fun little feature :)
