### ISSUE TITLE
App crashes when I type and call a number 

### ISSUE THREAD

**Issue by macspeaks** [Chooloo/call_manage#35]
**Describe the bug**
The app crashes every time I type a number and place a call. 

**To Reproduce**
1. Launch the app
2. Click on dialer 
3. Type the number you want to call and call 
4. The app will crash

**Expected behavior**
I expected the app to call the person instead it crashes 

**Video proof**
https://youtu.be/8cwmCF_9v1Y

**Smartphone (please complete the following information):**
 - Device: [Infinix note 4 ]
 - OS: [Android 7.0]
 - Version [ joker v0.3.1]

**Additional context**
Here's my phone full logcat report to assist you 
https://drive.google.com/file/d/1Fg-37psOVUpq1g0VOgFdK6Kjgd-Snh1x/view?usp=drivesdk

**Comment by JorikSchellekens** [comment]
I'm having the same issue. But being stuck with Huawei spy phone I'm very keen to contrib.

**Comment by roeiedri** [comment]
Hey were back!
Could you help us fix this? We think the problem might be related with the page trying to display contact's name, Does the number you typed saved as a contact? if so is the name special (special letters etc) And does it happen with every number? 
Thank You!

**Comment by roeiedri** [comment]
I worked on the bug and pretty sure i solved it, would you like to get the fixed version before it rolls out? because that will take time
