### ISSUE TITLE
Animation Glitch when switching quickly from Excel to Contacts

### ISSUE THREAD

**Issue by KhushrajRathod** [Chooloo/call_manage#56]
**Describe the bug**
There's an animation delay when switching quickly from excel to contacts, however switching between recents and contacts does not produce any such problem

**To Reproduce**
1. Go to 'Excel'
2. Swipe right twice to reach contacts (BTW the labels are reversed)

**Expected behavior**
Smooth Animation

**Screen Recordings**
![gif](https://user-images.githubusercontent.com/44947946/82698164-d4891f00-9c59-11ea-9fef-489c69592864.gif)

**Smartphone (please complete the following information):**
 - Device: Redmi 7A
 - OS: AOSP 10
 - Browser: What.
 - Version: [v216 GSI](https://github.com/phhusson/treble_experimentations/releases/tag/v216)

**Comment by roeiedri** [comment]
It's not a glitch, it's due to the app trying to load the excel app, sorry :)
Btw the reversed headers thing was fixed in a newer version
