### ISSUE TITLE
Dialing contacts with country codes failing

### ISSUE THREAD

**Issue by KhushrajRathod** [Chooloo/call_manage#58]
**Describe the bug**
Contacts with country codes are dialed without +, causing calls to fail (number does not exist)

**To Reproduce**
1. Add a contact with a country code
2. Call the contact

**Expected behavior**
There should be a plus before the country code and the call should succeed

**Smartphone (please complete the following information):**
 - Device: Redmi 7A
 - OS: Android 10
 - Browser: What.
 - Version: Phhusson AOSP GSI v221

**Comment by kpalang** [comment]
Same issue here. An example of a number with (Estonian) countrycode would be +372 1234 5678, where the dialed number will be just 372 1234 5678.

**Comment by roeiedri** [comment]
Is still an issue?

**Comment by KhushrajRathod** [comment]
> Is still an issue?

Yes, I just checked and the issue didn't magically fix itself 😄
