### ISSUE TITLE
Hanging when dialing mobile number 

### ISSUE THREAD

**Issue by Twiub** [Chooloo/call_manage#60]
I was dialing the number 0710269219. The app got stack every time I dialed 9. Am using Nokia 7.2 android 10
![Screenshot_20200524-222354](https://user-images.githubusercontent.com/47822673/82763202-92550e80-9e0e-11ea-9714-66b2fbec70a4.png)

**Comment by strel** [comment]
https://github.com/Chooloo/call_manage/issues/72
