### ISSUE TITLE
Removing + on saved international contacts. 

### ISSUE THREAD

**Issue by Twiub** [Chooloo/call_manage#62]
I have realised the saved international contacts the + is removed in contact and this make the number useless because a call cannot go through

Another thing it removes 0 on locally saved number and this make the saved number useless a call cannot go through.

Am using Nokia 7.2 android 10 
![Screenshot_20200525-092836](https://user-images.githubusercontent.com/47822673/82784910-2dc79d00-9e6a-11ea-8a1c-6ecde5ab6fc8.png)
![Screenshot_20200525-092854](https://user-images.githubusercontent.com/47822673/82784920-328c5100-9e6a-11ea-87f5-5fe9e95ced90.png)

**Comment by KhushrajRathod** [comment]
Please follow here: https://github.com/Chooloo/call_manage/issues/58
