### ISSUE TITLE
Calling numbers like (xxx) xxxxx crashing app

### ISSUE THREAD

**Issue by luukatyuo** [Chooloo/call_manage#65]
**Describe the bug**
When I hit a number like 3555 55246 in Firefox Koler works fine. If i click a nr like (3555) 55246 in firefox or copy it and insert it in Koler manually the screen goes black. Phone needs to be reactivated then. Koler will be stuck for some seconds before it s usable again. 

Versions
Koler is up2date 
Android 8 stock rom (up2date)

**Comment by paveltech** [comment]
I am also facing this issue

**Comment by paveltech** [comment]
I solved this issue. In the DialpadFragment

 @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        mViewModel = ViewModelProviders.of(getActivity()).get(SharedDialViewModel.class);
        mViewModel.getNumber().observe(this, s -> {
            if (!s.equals(Utilities.getOnlyNumbers(mDigits.getText().toString()))) {
                //setNumber(s);
            }
        });

just commit //setNumber(s); 
problem solved
