### ISSUE TITLE
Koler V0.2.7 -  Search Button And Button_Keypad Covers Star (*) And Hash (#) Button.

### ISSUE THREAD

**Issue by realrufans** [Chooloo/call_manage#7]
#### Expected behavior
I except both the search and ```button_keyboard``` button not to display when the user is using the ```Table_Numbers```.

#### Actual behavior

When the Star ( * ) button is pressed, it turns the interface into a search page while ```Table_Numbers``` is still active on the screen. And if the user presses the back button, Search Button And ```Button_Keypad``` Covers Star ( * ) And Hash (#) Button.
 

#### How to reproduce
- launch Koler, then, locate the interface to press a number
- click on the Star ( * ) button (at times, you might need to click it more than once)
- Watch it turn the interface into a search interface
- click back button, then, you will notice that the Search Button And Button_Keypad will cover the Star ( * ) And Hash (#) Button.

##### Browser/App version:
Koler v0.27

##### Operating system:
Android 0

#### Recording Of The Bug

![](https://i.imgur.com/kdJZ7fU.gif)

**Comment by realrufans** [comment]
Alternatively, calling and dropping a call will reproduce this issue.

**Comment by NuclearGandhi** [comment]
Fixed on 9f19a70a701ccca1f6bd4019ad868bf17e1928e5 and 6120e937ca8b7ba9788eff07f51b474de59bad66
