### ISSUE TITLE
Hold Buttons For More Actions

### ISSUE THREAD

**Issue by 532910** [Chooloo/call_manage#75]
![image](https://user-images.githubusercontent.com/14617699/86498606-35defa80-bd8f-11ea-8825-afa21dec2b82.png)

https://github.com/Chooloo/call_manage/blob/1a9871b94afe9904c0dc7b0a03e5c6f6824bd7d8/app/src/main/res/values/strings.xml#L25

There is only one button. It must be `Hold Button For More Actions`.

**Comment by strel** [comment]
That string is used also for answering, with two buttons available to hold for actions.

**Comment by 532910** [comment]
so there must be two different strings
