### ISSUE TITLE
action_call doesn't work on andriod 10  

### ISSUE THREAD

**Issue by greate43** [Chooloo/call_manage#76]
- When you try and make a call on android physical device . the ui for calling someone is showing but the call isn't going through plus no dial tone  is being heard.  

- when selecting sim slots in call manager. their is a parsing exception being throw .

**Comment by Allay054** [comment]
Same issue on my side as well

**Comment by greate43** [comment]
for the parsing exception
in PrefreanceUitl class add this line
`sDefaultValues.put(R.string.pref_sim_select_key, context.getString(R.string.pref_sim_select_default_value));
`
and in the CallManager class change this line
`return Integer.parseInt(String.valueOf(PreferenceUtils.getInstance(context).getString(R.string.pref_sim_select_key)));
`

here is how you can solve the dial tone issue you need to select the account handle and pass it as a extra  
```
 try {
            List<PhoneAccountHandle> phoneAccountHandleList = TelecomUtil.getTelecomManager(context).getCallCapablePhoneAccounts();
            int simCard = getSimSelection(context);

            // Create call intent
            Intent callIntent = new Intent(Intent.ACTION_CALL, Uri.parse("tel:" + Uri.encode(number)));

            if (phoneAccountHandleList != null && !phoneAccountHandleList.isEmpty()) {
                callIntent.putExtra(TelecomManager.EXTRA_PHONE_ACCOUNT_HANDLE, phoneAccountHandleList.get(simCard));
            }
//            // Handle sim card selection
            Timber.d("simcard %s", simCard);
            if (simCard != -1) callIntent.putExtra("com.android.phone.extra.slot", simCard);
//            // Start the call
            context.startActivity(callIntent);

        } catch (SecurityException e) {
            Toast.makeText(context, "Couldn't make a call due to security reasons", Toast.LENGTH_LONG).show();
        } catch (NullPointerException e) {
            Toast.makeText(context, "Couldnt make a call, no phone number", Toast.LENGTH_LONG).show();
        }
```

**Comment by roeiedri** [comment]
can you elaborate about the issue with the sim selection, what was the bug you fixed? 
And btw thank you very much ill implements that asap

**Comment by greate43** [comment]
@roeiedri 
1) The first bug is If you are using a dual sim phones and from phone setting if you haven't pre-selected a sim then the app wont be able to make a call and will require you to pass EXTRA_PHONE_ACCOUNT_HANDLE in the intent.
2) the telecom manager class just have this code  
 ```
static TelecomManager getTelecomManager(Context context) {
        return (TelecomManager) context.getSystemService(Context.TELECOM_SERVICE);
    }
```
3) the second bug is when you try to getSelection() in the call() method it throw an exceptions saying couldnt select a sim card. that happens because of   CallManager class method  getSimSelection() change that line were you return the value to this
`return Integer.parseInt(String.valueOf(PreferenceUtils.getInstance(context).getString(R.string.pref_sim_select_key)));`

and in the preferenceutil add this line to set the default value for sim selection
` sDefaultValues.put(R.string.pref_sim_select_key, context.getString(R.string.pref_sim_select_default_value));
`

**Comment by roeiedri** [comment]
awesome man thanks
one last thing, there is no function called `getCallCapablePhoneAccounts()`

**Comment by greate43** [comment]
its a built-in method of telecom manager class

**Comment by roeiedri** [comment]
here's the code, it says the function doesn't exist
` List<PhoneAccountHandle> phoneAccountHandleList = (TelecomManager) context.getSystemService(Context.TELECOM_SERVICE).getCallCapablePhoneAccounts();`

**Comment by greate43** [comment]
TelecomManager telecomManager = (TelecomManager) context.getSystemService(Context.TELECOM_SERVICE);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            telecomManager.getCallCapablePhoneAccounts()
        }
works for me like this

**Comment by roeiedri** [comment]
Oh yeah because i made it in one line it didn't return the telecom manager.
Great im adding your solution and ill push an update soon

**Comment by greate43** [comment]
that's great happy to help.
