### ISSUE TITLE
Call is not going

### ISSUE THREAD

**Issue by Allay054** [Chooloo/call_manage#77]
When i try to make a call using this application
Outgoing call is not working

**Comment by Allay054** [comment]
Outgoing working fine for android 8.0
But when run on android 9 and 10 
Outgoing call not working

**Comment by khalil054** [comment]
Same Issue on My Side as well

Outgoing working fine for android 8.0
But when run on android 9 and 10
Outgoing call not working

**Comment by greate43** [comment]
here is my solution . I solved it  
https://github.com/Chooloo/call_manage/issues/76#issuecomment-680970419

**Comment by roeiedri** [comment]
Solved in #76
