### ISSUE TITLE
Latest versions are missing at Github releases

### ISSUE THREAD

**Issue by IzzySoft** [Chooloo/call_manage#80]
The ReadMe says the app is available for download at releases. Last version there is v0.3.1 dated 6/2019 – while Play Store lists v0.5.5 dated 8/2020. Will up-to-date versions be made available here again at some point?

**Comment by roeiedri** [comment]
Where do u mean latest version is 0.3.1? look at 'restructre' branch
And yes everthing is a bit off
Ill organize all that once i get the chance

**Comment by IzzySoft** [comment]
> Where do u mean latest version is 0.3.1?

At https://github.com/Chooloo/call_manage/releases – where your ReadMe [says to look](https://github.com/Chooloo/call_manage#get-the-app) :wink: Could you add at least the current release (0.5.5) there, with its APK? Adding all the intermediate releases would probably be a bit overkill.

> Ill organize all that once i get the chance

Thanks a lot!

**Comment by roeiedri** [comment]
Added the latest version, not fully fully production ready but its the latest code

**Comment by IzzySoft** [comment]
Thanks a lot!

**Comment by IzzySoft** [comment]
May I nag you again, @roeidri? Last tag is 0.5.6, gradle says 0.6.2 – so it looks like you've missed a few releases again.

**Comment by roeiedri** [comment]
Removed the app from play store and stopped supporting production, no
support
Currently slowly working on a new improved code as the old one was pretty
bad
U can take a look at the "mvp" branch

**Comment by IzzySoft** [comment]
Oh, that's sad news (the first sentence). So you won't even provide the last release you've made I guess? But good luck with the rewrite then! Not being a dev, I of course could take a look at the mvp branch, but it won't help either you or me :laughing:

**Comment by IzzySoft** [comment]
I see you've picked up releases again, @roeiedri – but my auto-updater fails as the APKs attached there seem to use a different package name now (`com.chooloo.www.koler` instead of `com.chooloo.www.callmanager`). Is that intended? That essentially makes it a different app, so no updating possible at the user's end.

**Comment by roeiedri** [comment]
Yes ive changed the package name

**Comment by IzzySoft** [comment]
Ah, OK. That means some work then "further down". I hope you don't plan to do that again? Just asking :wink:

**Comment by roeiedri** [comment]
Yeah i was just getting so annoyed from that callmanager name so i had to
Dont worry :)

Btw i didnt know itll be a problem so sorry

**Comment by IzzySoft** [comment]
Yeah, I'm just renaming it in my repo now. Anyone who had it installed will be confused it's gone, and has to find it again via manual search then – plus install the new version manually, transfer any configuration, then delete the original app. If they notice it at all, that is – there's no notification of "please change to the new app". So some might run for a while on outdated versions before wondering and checking manually.

**Comment by roeiedri** [comment]
Yeah oopsie
Dumb move

**Comment by IzzySoft** [comment]
Too late now… Just remember for next time :rofl:
