### ISSUE TITLE
Speaker phone bug

### ISSUE THREAD

**Issue by abh-oss01** [Chooloo/call_manage#82]
**Describe the bug**
Speaker phone **does not** work. 

**To Reproduce**
1. Accept a call
2. Click on 'Speaker Phone' icon
3. It doesn't turn on, even after repeatedly trying toggling the button.

**Expected behavior**
It should turn the speaker phone ON.

**Screenshots**
I don't have any at the moment.

**Smartphone (please complete the following information):**
 - Device: Realme 6 pro
 - OS: Android 10

**Comment by roeiedri** [comment]
it should now work, if not just open this issue again

**Comment by abh-oss01** [comment]
Is there an update on f-droid?
I haven't received any yet, hence asking.

**Comment by roeiedri** [comment]
Im not posting updates on f-droid... sorry :/

**Comment by abh-oss01** [comment]
what? didn't understand 😅

**Comment by roeiedri** [comment]
There is no update on f-droid
There is an update on google play store

**Comment by abh-oss01** [comment]
why not fdroid

**Comment by roeiedri** [comment]
I'm just not so familiar with it and don't have much time to mess with it

**Comment by abh-oss01** [comment]
ok, well it's your choice...
but I didn't get a updat on play store yet.
do I have to enroll in beta? (because I haven't yet, since I downloaded the app from fdroid)

**Comment by roeiedri** [comment]
Oh yeah it might take some time maybe tomorrow
The app is waiting for Google's review and they said due to the corona situation stuff migh take some more time
