### ISSUE TITLE
Contact Info/Edit Broken

### ISSUE THREAD

**Issue by UltraBlackLinux** [Chooloo/call_manage#83]
**Describe the bug**
Editing and showing contact info doeant work.

**To Reproduce**
1. Click on edit contact: Error while opening the editor
2. Click on Info: This contact doesnt exist

**Expected behavior**
Show info/edit contact

**Smartphone (please complete the following information):**
 - Device: Razer Phone
 - OS: Android 10

**Comment by roeiedri** [comment]
Does it happen with every contact? Does it have a certain pattern with related numbers? or randomly?

**Comment by UltraBlackLinux** [comment]
@roeiedri It happens every time.
