### ISSUE TITLE
Koler V0.2.7 -  Recent Page Doesn't Hold The Call History

### ISSUE THREAD

**Issue by realrufans** [Chooloo/call_manage#9]
#### Expected behavior
To save call logs.

#### Actual behavior
It doesn't save them any of the calls made in the past.
 

#### How to reproduce
- launch Koler, then, locate the interface to dial a number
- Dial a number, then, end the call
- Navigate to the recent interface 
- You will notice that it won't save the call.

##### Browser/App version:
Koler v0.27

##### Operating system:
Android 0

#### Recording Of The Bug

![MNML-May16-1135-1558003043411.gif](https://cdn.steemitimages.com/DQmbhqeBt1Fx42TBcxYn4cy7qX64iihhwoatQLBhGTwNpHP/MNML-May16-1135-1558003043411.gif)

**Comment by NuclearGandhi** [comment]
Fixed on 880dbefb71b93849ec86bd64ba05d79cbf0f5403

**Comment by realrufans** [comment]
Awesome

I will update the project on AS
