### ISSUE TITLE
Closing the dial pad closes the app

### ISSUE THREAD

**Issue by 98h398hrpohpoai** [Chooloo/call_manage#90]
**Describe the bug**
When opening the dialer pad and then navigating backward either through the nav bar or gesture, the entire app closes (or goes back in the "app history" e.g. back to settings if that menu was open, and then back to contacts/recents/etc.).

**To Reproduce**
1. Open the app
2. Go to settings
3. Change a setting.
4. Go back to contacts or recent calls.
5. Open the dial pad.
6. Navigate "Back" (either gesture or nav bar).
7. Goes to previous menu, or closes the app if skipping steps 1-4.
---
8. Just noticed this--doing this under the "Recents" menu keeps the "+" button present as well. That should probably disappear when opening the dialer.

**Expected behavior**
When pressing the back button with the dial pad open, the dial pad should minimize to it's previous state and show either contacts or recent calls.

**Screenshots**

**Smartphone (please complete the following information):**
Tested on a Pixel 4 XL running Android 10 and 11 (Graphene OS)
 
**Additional context**

**Comment by roeiedri** [comment]
This was fixed in last commit.. A new update will roll out soon
