### ISSUE TITLE
Calling screen content jumps if contact name is smaller than status text

### ISSUE THREAD

**Issue by zhirzh** [Chooloo/call_manage#96]
**Describe the bug**
Calling screen content jumps if contact name is smaller than status text because of center alignment of content

**To Reproduce**
1. Create a contact with a small name
1. Call the contact
1. Observe the contact info & call status

**Screenshots**

![1 - call with short name](https://user-images.githubusercontent.com/8132723/94448772-f0cd3780-01c8-11eb-98e2-c2b3de43b716.gif)

**Comment by roeiedri** [comment]
That's kind off intentional... seeing something moving on the screen just make the change of the status a bit more obvious
Does it look bad in your opinion?

**Comment by zhirzh** [comment]
It doesn't feen intentional because if the name is _long enough_, there's no such jumping.

I think it's related to the center alignment of contact info in `on_going_call.xml`. When the contact name is small, `text_layout` element gets its width from the `text_status` element. When status text changes, the width of the `text_layout` also changes.

This causes the jump.

**Comment by roeiedri** [comment]
Thanks, ill change it
